import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  intro: ["intro"],
  frontend: [{ type: "autogenerated", dirName: "frontend" }],
  backend: [{ type: "autogenerated", dirName: "backend" }],
};

export default sidebars;
