import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  letha: [
    "intro",
    "scrollycoding",
    {
      type: "category",
      label: "Authentication",
      link: {
        type: "generated-index",
        title: "Authentication",
        description: "Basic learning",
        slug: "/category/authentication/intro",
        keywords: ["guides"],
      },
      items: ["authentication/jwt"],
    },
  ],
  sfm: [{ type: "autogenerated", dirName: "sfm" }],
};

export default sidebars;
