import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const backendSidebars: SidebarsConfig = {
  backend: [{ type: "autogenerated", dirName: "." }],
};

export default backendSidebars;
